/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SnSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "titleText": string;
    }
    interface SnSpinner {
    }
    interface SnStockFinder {
    }
    interface SnStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLSnSideDrawerElement extends Components.SnSideDrawer, HTMLStencilElement {
    }
    var HTMLSnSideDrawerElement: {
        prototype: HTMLSnSideDrawerElement;
        new (): HTMLSnSideDrawerElement;
    };
    interface HTMLSnSpinnerElement extends Components.SnSpinner, HTMLStencilElement {
    }
    var HTMLSnSpinnerElement: {
        prototype: HTMLSnSpinnerElement;
        new (): HTMLSnSpinnerElement;
    };
    interface HTMLSnStockFinderElement extends Components.SnStockFinder, HTMLStencilElement {
    }
    var HTMLSnStockFinderElement: {
        prototype: HTMLSnStockFinderElement;
        new (): HTMLSnStockFinderElement;
    };
    interface HTMLSnStockPriceElement extends Components.SnStockPrice, HTMLStencilElement {
    }
    var HTMLSnStockPriceElement: {
        prototype: HTMLSnStockPriceElement;
        new (): HTMLSnStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "sn-side-drawer": HTMLSnSideDrawerElement;
        "sn-spinner": HTMLSnSpinnerElement;
        "sn-stock-finder": HTMLSnStockFinderElement;
        "sn-stock-price": HTMLSnStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface SnSideDrawer {
        "opened"?: boolean;
        "titleText"?: string;
    }
    interface SnSpinner {
    }
    interface SnStockFinder {
        "onSnSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface SnStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "sn-side-drawer": SnSideDrawer;
        "sn-spinner": SnSpinner;
        "sn-stock-finder": SnStockFinder;
        "sn-stock-price": SnStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sn-side-drawer": LocalJSX.SnSideDrawer & JSXBase.HTMLAttributes<HTMLSnSideDrawerElement>;
            "sn-spinner": LocalJSX.SnSpinner & JSXBase.HTMLAttributes<HTMLSnSpinnerElement>;
            "sn-stock-finder": LocalJSX.SnStockFinder & JSXBase.HTMLAttributes<HTMLSnStockFinderElement>;
            "sn-stock-price": LocalJSX.SnStockPrice & JSXBase.HTMLAttributes<HTMLSnStockPriceElement>;
        }
    }
}
